### ISSUE TITLE
Add Electrons from MultiClusters in the ntuplizer

### ISSUE THREAD

**Issue by rovere** [CMS-HGCAL/reco-ntuples#47]
Dear all, 
instead of writing a longish email to explain something that should be already clear from the subject, I just paste here the link to the comparison between my branch and the current HEAD with all the changes I propose to include.

Besides adding electrons (and their associated multiclusters decomposed in PFClusters), I also added a very simple python prototype to be used for quick analysis, with a rudimentary Zee example. Maybe you can find it useful.

https://github.com/CMS-HGCAL/reco-ntuples/compare/master...rovere:devel?w=1

**Comment by artlbv** [comment]
Hi Marco, 
I think it might be more convenient to review and comment on these changes within a PR.
One thing I'm wondering about: why did you include the `ntupleDataFormat.py` from the other repository here? Is there a plan to merge these two repos? @clelange

**Comment by rovere** [comment]
@artlbv I simply ignored the existence of the other repository up to now.
We can keep as many separate repositories as we want like, I have no problems working with submodules in GitHub. If so, I can push the changes in the other repo. 3 repos, for me, are 2 too much, but I can adapt to whatever you judge is better.

**Comment by rovere** [comment]
@artlbv, especially since the format of the n-tuple in one repo is affecting the analysis fwk in the other, and you have to have them in sync by hand....

**Comment by clelange** [comment]
The separate repositories were introduced in order no to force people to work with a specific analysis script and also the sample production scripts are CERN specific and therefore not applicable for e.g. people at FNAL. This means some extra work, but then again convinced more people to use parts of it.
Regarding the code changes - it'll be difficult to merge this since you changed a lot of variable names (e.g. appending `_`), so reviewing this is (unnecessarily?) time-consuming. It would be great if you created a PR with only relevant lines changed.

**Comment by rovere** [comment]
@clelange variable names' changes will be part of the final PR and are not unnecessary: on the contrary, they will save quite a bit of time while reading and understanding the code. The PR will come as soon as I find the time to work on it.
On the separation of production from "ntuple-world" I agree. On the separation of Python FWK and ntuple, as I said, I disagree but I leave the final call to you since you'll be managing PRs.
